# Generated by Django 5.0.6 on 2024-05-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=255)),
                ('작성자', models.CharField(max_length=255)),
                ('내용', models.TextField()),
                ('작성일', models.DateField()),
                ('수정일', models.DateField()),
                ('조회수', models.IntegerField()),
            ],
        ),
    ]
