# Generated by Django 5.0.6 on 2024-05-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0002_reply_alter_border_수정일_alter_border_작성일'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='댓글수',
            field=models.IntegerField(default=0),
        ),
    ]
