# Generated by Django 5.0.6 on 2024-05-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0003_border_댓글수'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('좋아요', models.FileField(upload_to='images/')),
                ('싫어요', models.FileField(upload_to='images/')),
            ],
        ),
    ]
