# Generated by Django 5.0.6 on 2024-05-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='border',
            name='싫어요',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='border',
            name='좋아요',
            field=models.IntegerField(default=0),
        ),
    ]
